### ISSUE TITLE
Default admin password?

### ISSUE THREAD

**Issue by CyberSecGuy** [YunoHost-Apps/owncast_ynh#16]
I've installed OwnCast on YunoHost, and the documentation says username / password is -- admin / abc123

I'm unable to log into the admin panel. Please advise.

- Also did a grep -r -H "abc123" on the /var/www/owncast directory, and I'm getting zero hits.

**Comment by ericgaspar** [comment]
Are you using Firefox? Have you tested with Chromium?
I have this problem with Firefox but not with other browsers ... very strange

**Comment by CyberSecGuy** [comment]
Crazy, just tried **with** firefox, and it worked. It does not work for me on Chrome. It must be the way it's saving cookies.
