### ISSUE TITLE
Can't login with default credentials

### ISSUE THREAD

**Issue by Tagadda** [YunoHost-Apps/owncast_ynh#23]
### Describe the bug

Can't login with default credentials

### Context

- Hardware: VPS bought online
- YunoHost version: 4.3.6.3 
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: master

### Steps to reproduce

- Install the app
- Try to login to /admin with `admin` and `abc123`

### Expected behavior

Successful login.

### Logs

**Comment by ericgaspar** [comment]
what port did you open? `8095`

**Comment by Michcioperz** [comment]
It was 8096 for me, my understanding of YunoHost is that it assigns http ports sequentially to applications. I am new to YunoHost so I don't know what the right way to find out the assigned port is. I used good old `ss -ntlp` command over ssh as root to find out which port is used by Owncast.

**Comment by RengeLK** [comment]
Admin login seems to only work when I am not signed in to the SSO

**Comment by yashodhank** [comment]
Yes, unable to login to admin using default credentials.
SSO creates issues with login to admin if you have disabled anonymous access during installation of this app.

**Comment by kamazeuci** [comment]
this is still happening to me in latest version

**Comment by Hezkore** [comment]
Same.

**Comment by thefrankring** [comment]
This is still happening to me with
- yunohost 12.1.36
- owncast 0.2.3

The SSO makes it impossible to log in with owncast's default credentials
