### ISSUE TITLE
0.0.13~ynh1 not updating owncast to 0.0.13

### ISSUE THREAD

**Issue by taintedcypher** [YunoHost-Apps/owncast_ynh#28]
### Describe the bug

Updating Owncast package from `0.0.12~ynh1` to `0.0.13~ynh1` does not update Owncast to 0.0.13. Version stays 0.0.12.

### Context

- Hardware: VPS (ovhcloud)
- YunoHost version: 11.0.10.2 
- I have access to my server: Through SSH + through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: owncast 0.0.13~ynh1
- If upgrading, current package version: owncast 0.0.13~ynh1

### Steps to reproduce
Update owncast package from 0.0.12~ynh1 to 0.0.13~ynh1, through web ui (/yunohost/admin/#/update)

### Logs
https://paste.yunohost.org/raw/hedagiyaba

**Comment by xabirequejo** [comment]
Same issue here.

Hardware: Raspberry Pi 4B 8Gb
YunoHost: 11.1.0.2 (testing)
Upgrade: via webadmin

Webadmin says that app version is 0.0.13~ynh1, however both the user and admin areas of owncast keep saying 0.0.12 and encourage the upgrade to 0.0.13.

`YNH_APP_CURRENT_VERSION: 0.0.12~ynh1`
`YNH_APP_MANIFEST_VERSION: 0.0.13~ynh1`

[Log](https://paste.yunohost.org/raw/ketotuwihe)

**Comment by ericgaspar** [comment]
fixed with #29

**Comment by taintedcypher** [comment]
Hi again,
Thanks for the quick response!
However I just upgraded to 0.0.13~ynh2, but sadly owncast is still 0.0.12
Here are the logs: https://paste.yunohost.org/raw/cuniqihiqa
