### ISSUE TITLE
Owncast still 0.0.12 after upgrade from 0.0.13~ynh1 to 0.0.13~ynh2

### ISSUE THREAD

**Issue by taintedcypher** [YunoHost-Apps/owncast_ynh#30]
### Describe the bug
Package `0.0.13~ynh1` was pointing to upstream version of owncast 0.0.12, so it didn't update owncast.
A new package version (`0.0.13~ynh2`) was made available after it was fixed, however I just upgraded to 0.0.13~ynh2, but sadly owncast is still 0.0.12.

Unlike the logs in #28, there is not even a mention to the owncast repo [in the logs for this update](https://paste.yunohost.org/raw/cuniqihiqa). Aleks in the Yunohost support room (on Matrix) said "l'upgrade se comporte différemment si la version upstream a changé de si c'est juste le suffixe ~ynh qui change" ("The upgrade behaves differently when the upstream version changes than when only the ~yhn suffix changes").

Please tell me if you need anything else!

### Logs
Here are the logs: https://paste.yunohost.org/raw/cuniqihiqa

**Comment by 4sheper** [comment]
Same issue here.

**Logs**
https://paste.yunohost.org/raw/sogohufuwi

**Comment by taintedcypher** [comment]
For @4sheper and anyone else having this issue, here's what has worked for me:

```
sudo yunohost app upgrade owncast --force
```
After running the upgrade command from the cli with the --force flag, Owncast is now 0.0.13.
