### ISSUE TITLE
"401 Authorization Required nginx" error when accessing Admin panel

### ISSUE THREAD

**Issue by Szkodnix** [YunoHost-Apps/owncast_ynh#32]
### Describe the bug

Owncast used to work fine and I did not have any problems accessing Admin panel. Today however I was not able to login to it. When I tried to log in to admin panel I see a white message "401 Authorization Required nginx". Password is correct (streaming itself works and I copy-pasted password straight from OBS), tried clearing cache and cookies, no changes made in configuration of the server. Restoring OwnCast from backup via YunoHost did not work either. Changing stream key did not work as well.

### Context

- Hardware: VPS bought online (OVH)
- YunoHost version: 11.1.0.2
- I have access to my server: Through SSH | through the webadmin
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using: OwnCast 0.0.13~ynh2 (everything is up-to-date as of this moment, both OwnCast and YunoHost)

### Steps to reproduce

Just accessing the admin panel via https://live.szkod.ovh/admin/

### Expected behavior

White page with "401 Authorization Required nginx" error after submitting login and password (either correct or incorrect).

### Logs

https://paste.yunohost.org/sicoreyipi - OwnCast running
https://paste.yunohost.org/zofajojazi - nginx related to OwnCast

![obraz](https://user-images.githubusercontent.com/111020259/212175120-1722eb76-6eaf-406a-afdf-e62ce52eda1d.png)

**Comment by ericgaspar** [comment]
can you try `yunohost app ssowatconf` in a terminal?

**Comment by Szkodnix** [comment]
Hi eric!

I really appreciate your reply! I tried it (as root) and I didn't see either any result in Terminal or any change in OwnCast behavior. What was supposed to happen?

**Comment by ericgaspar** [comment]
We had some issues with 401 errors with a few apps due to a recent update.
I am able to reach your Owncast admin page (with credential popup)

**Comment by Szkodnix** [comment]
Okay, I understand.
Credential popup works, however when I put correct credentials there is an error that I have previously shown.

**Comment by ericgaspar** [comment]
Can you try different browser.s? (I have issues connecting with Firefox but not with Opera)

**Comment by Szkodnix** [comment]
Firefox, Edge and Chrome (on a separate laptop) have the same error when trying to log in.

**Comment by ericgaspar** [comment]
I can't reproduce the issue on a fresh install... I am short on idea

**Comment by Szkodnix** [comment]
I understand. It used to work for me too on Tuesday. Today it just changed without my actions. Still thanks for trying.

**Comment by Szkodnix** [comment]
Issue seems to have been fixed in Yunohost 11.1.5.4. Closing issue.
